import "./style.scss";
import 'materialize-css'
import "./index.css";
import "./images/REC.png";
import "./images/TPP.png";
import "./images/EEC.png";
import "./images/CCPIT.png";
import "./images/HYVE.png";
import "./images/MF.png";
import "./images/SLOVAK.jpg";
import "./images/GAZ.svg";
import "./images/ASI.png";
import "./images/RUCH.jpg";
import "./images/HUAMIN.jpg";
import "./images/SKOLTECH.png";
import "./images/MYB.png";
import "./images/MEC.png";
import "./images/DHH.png";
import "./images/BRICS.png";
import "./images/RCC.png";
import "./images/MMI.png";
import "./images/EXPO.jpg";
import "./images/ISPSNG.png";
import "./images/HEPA.jpg";
import "./images/LIB.jpg";
import "./images/telegram.png";
import "./images/facebook.png";
import "./images/instagram.png";

import "./images/global.svg";
import "./images/growth.svg";
import "./images/boss.png";
import "./images/influencer.png";
import "./images/computer.svg";
import "./images/consult.png";

